#!/bin/bash -x

# Generate HTML source

html="${out%.*}.html"

cat <<END > $html
<video controls>
<source src=$(basename "$out") type=video/mp4>
</video>
END

ffprobe -v quiet -print_format json -show_streams -show_format "$out" > "$out.json"
